# Site settings
title: Solo Press
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  Solo Press has been publishing poetry since 1966.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/
  books:
    output: true
    permalink: /books/:path/
