<div id="menu">
    <div class="pure-menu pure-menu-open pure-menu-horizontal">
        <a class="pure-menu-heading" href="/">
          <img class="logo" src="{{ site.url }}/img/logo.png" width="100" alt="" />
        </a>
        <ul>
            <li><a href="/news/">News</a></li>
            <li><a href="/books/">Books</a></li>
            <li><a href="/about/">About</a></li>
            <li><a href="https://www.facebook.com/solopressSLO/">Facebook</a></li>
        </ul>
    </div>
</div>
