<section class="news">
	<div class="row">
		<h1>News</h1>
		<div class="pure-g">
			<div class="pure-u-1 pure-u-md-1-3">
				<p>Jeanie Greensfelder is currently serving as San Luis Obispo County’s poet laureate during 2017, 2018.</p>
			</div>
			<div class="pure-u-1 pure-u-md-2-3">
				<p>Hear Garrison Keillor read Jeanie's poem “First Love” on the <a href="http://writersalmanac.org/episodes/20141103/">November 3, 2014 episode of <em>The Writer's Almanac</em></a>.</p>
			</div>
			<div class="pure-u-1 pure-u-md-2-3">
				<blockquote>Greensfelder achieves accessibility, and Biting the Apple would be a good collection to hand to any person who claims not to be able to understand contemporary poetry.</blockquote>
				<p>— From <a href="http://lynndomina.com/?p=228">Lynn Domina's review of <em>Biting the Apple</em></a></p>
			</div>
			<div class="pure-u-1 pure-u-md-1-3">
				<p>Watch Craig Michael Davis' performance of three songs inspired by Jeanie's poems from <em>Biting the Apple</em> on <a href="https://www.youtube.com/watch?v=9LX3_RiwA5I">YouTube</a>.</p>
			</div>
			<div class="pure-u-1 pure-u-md-1-3">
				<p>Read Jeanie's poem <em>Sixth Grade</em>, featured at <em><a href="http://www.americanlifeinpoetry.org/columns/477.html">American Life in Poetry</a></em>.</p>
			</div>
			<div class="pure-u-1 pure-u-md-2-3">
				<p>Lean more about Jeanie Greensfelder at <a href="http://jeaniegreensfelder.alhteam.com/">her website</a>.</p>
			</div>
		</div>
	</div>
</section>
