<p>Toast is a weekly email newsletter and yearly printed anthology.</p>
<!-- Begin MailChimp Signup Form -->
<!-- Begin MailChimp Signup Form -->
<div id="mc_embed_signup">
<form action="https://solopress.us18.list-manage.com/subscribe/post?u=5057a3818583f8ee3496c049a&amp;id=9f99be121a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
  <h3>Subscribe to get Toast sent to your email</h3>
<div class="mc-field-group">
  <label for="mce-EMAIL">Email Address </label>
  <input type="email" class="toast-input" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
  <div id="mce-responses" class="clear">
    <div class="response" id="mce-error-response" style="display:none"></div>
    <div class="response" id="mce-success-response" style="display:none"></div>
  </div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_5057a3818583f8ee3496c049a_9f99be121a" tabindex="-1" value=""></div>
    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="button toast-submit"></div>
    </div>
</form>
</div>
<p class="post-meta">We only use your email address to send Toast, not for any nefarious purposes.</p>
<!--End mc_embed_signup-->
<ul>
  <li><strong>Glenna Luschei</strong>, Abiding Publisher and Editor Emeritus</li>
  <li><strong>Benjamin Daniel Lawless</strong>, Editor in Chief</li>
  <li><strong>Tom Harrington</strong>, International Editor</li>
  <li><strong>Rena Ferro</strong>, Managing Editor</li>
</ul>
