<p>Toast was a weekly email newsletter that ran from July 2018 to March 2019. All of the pieces from Toast’s run and more can be read in <a href="/books/solo-novo-5-6"><em>Solo Novo 5/6</em></a>.</p>

<ul>
  <li><strong>Glenna Luschei</strong>, Abiding Publisher and Editor Emeritus</li>
  <li><strong>Benjamin Daniel Lawless</strong>, Editor in Chief</li>
  <li><strong>Tom Harrington</strong>, Contributing Editor</li>
  <li><strong>Rena Ferro</strong>, Managing Editor</li>
  <li><strong>Brian Landis</strong>, Photographer and Advisor</li>
</ul>
